export default  {
  'SMER - SD': [
    'Monika Beňová',
    'Miroslav Číž',
    'Róbert Hajšel',
    'Katarína Roth Neveďalová',
    'Igor Melicher',
    'Martin Lancz',
    'Ján Mažgút',
    'Richard Eliáš',
    'Ladislav Rolník',
    'Peter Voľanský',
    'Veronika Murková',
    'Zdenko Svoboda',
    'Martin Karaš',
    'Peter Hanulík',
  ],
  'Kresťanská demokracia - Život a prosperita': [
    'Štefan Kuffa',
    'Marián Tkáč',
    'Viliam Oberhauser',
    'Marián Servátka',
    'Tomáš Janco',
    'Mária Benová',
    'Matej Šarocký',
    'Miroslav Vetrík',
    'Darius Hatok',
    'Filip Kuffa',
    'Jozef Liday',
    'Karina Pénzešová',
    'Pavol Nižnánsky',
  ],
  'Kotleba - Ľudová strana Naše Slovensko (ĽS NS)': [
    'Martin Beluský',
    'Milan Mazurek',
    'Miroslav Radačovský',
    'Lukáš Kopáč',
    'Miroslav Urban',
    'Karol Polanský',
    'Lucia Žužová',
    'Ondrej Ďurica',
    'Lenka Bočkayová',
    'Marek Kotleba',
    'Miloš Zverina',
    'Jozef Mihalčin',
    'Norbert Lichtner',
    'Milan Uhrík',
  ],
  'Korektúra - Andrej Hryc': [
    'Andrej Hryc',
  ],
  'Slovenská národná strana (SNS)': [
    'Jaroslav Paška',
    'Karol Farkašovský',
    'Pavol Dubček',
    'Karol Konárik',
    'Maroš Pavlovič',
    'Ján Krišanda',
    'Eva Milučká',
    'Jaroslav Barcaj',
    'Jana Beňáková Tulisová',
    'Vladimír Fraňo',
    'Ján Holodňák',
    'Martin Čornej',
    'Monika Gergeľová',
    'Tibor Jančula',
  ],
  'SME RODINA - Boris Kollár': [
    'Peter Pčolinský',
    'Ľudovít Goga',
    'Petra Krištúfková',
    'Ivan Bella',
    'Sylvia Kulasik',
    'Dušan Doliak',
    'Eva Hudecová',
    'Dominika Sabová',
    'Jozef Mozol',
    'Tomáš Gbúr',
    'Michal Gašaj',
    'Rastislav Masnyk',
    'Dalibor Steindl',
    'Martin Dzielavský',
  ],
  'OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO)': [
    'Igor Matovič',
    'Michal Šipoš',
    'Peter Pollák',
    'Zita Pleštinská',
    'Dominik Drdul',
    'Eva Horváthová',
    'Milan Potocký',
    'Lucia Greškovitsová',
    'Igor Dušenka',
    'Dušan Šándor',
    'Lucia Rennerová',
    'Pavol Jusko',
    'Eva Ivanovová',
    'Matúš Bystriansky',
  ],
  'Starostovia a nezávislí kandidáti': [
    'Martina Šimkovičová',
    'Martin Hoza',
    'Martin Augustín',
    'Ľubomír Šesták',
    'Henrieta Dvorská',
    'Tatiana Simona Demová',
  ],
  'Strana práce': [
    'Filip Danninger',
    'Michal Buraľ',
    'Marian Vidiščák',
    'Zuzana Štrbíková',
    'Adrián Ondrovič',
    'Lenka Humajová',
    'Jaroslava Marcineková',
  ],
  'Strana tolerancie a spolunažívania': [
    'Viktor Valik',
    'Ján Lacko',
    'František Tanko',
    'Petra Kamenárová',
    'Dezider Bilý',
    'Róbert Bodiš',
    'Jaroslav Tokár',
    'Vojtech Tancoš',
    'Martin Somora',
  ],
  'Hlas ľudu': [
    'Peter Marček',
    'Márius Hričovský',
    'Roman Bušo',
    'Róbert Pukalovič',
    'Ondrej Štefik',
    'Martin Graus',
    'Zdena Patakyová',
    'Tibor Belovič',
    'Marek Školuda',
    'Rastislav Lehotský',
    'Ľubomír Schmida',
    'Dušan Marušák',
    'Marian Hlavatovič',
    'Gené Martan',
  ],
  'Maďarská kresťanskodemokratická aliancia': [
    'Károly Less',
    'Zoltán Bogoly',
    'Agáta Janková',
    'Roland Bánhegyi',
    'Péter Fehér',
    'Jozef Mikus',
    'Eva Šinková',
    'Gejza Dubovicky',
    'Eleonóra Majorová',
    'Viktória Seresová',
    'Tamás Miško',
    'Jácint Kecskeméti',
    'Peter Galko',
    'Bianka Czetőová',
  ],
  'DOPRAVA': [
    'Marián Damankoš',
    'Ján Cirák',
    'Lenka Beňačková',
    'Ludvík Posolda',
    'Ľubomír Ochotnický',
    'Roman Hrnčirík',
    'Jozef Mišenko',
    'Adriana Trojanovičová',
    'Tomáš Beharka',
    'Jaroslav Mäsiar',
    'Jaroslav Málek',
    'Viktor Magic',
  ],
  'Kresťanskodemokratické hnutie (KDH)': [
    'Ivan Štefanec',
    'Miriam Lexmann',
    'Marián Čaučík',
    'Andrej Klapica',
    'Miriam Kuzárová',
    'Lucia Gurbáľová',
    'Ján Hencel',
    'Michal Považan',
    'Veronika Jankovičová',
    'Radoslav Kozák',
    'Ondrej Tunega',
    'Martin Šmilňák',
    'Tomáš Merašický',
    'Ján Figeľ',
  ],
  'Strana zelených Slovenska': [
    'Martin Čulen',
    'Roman Kollár',
    'Michal Krištof',
    'Silvia Mackovičová',
    'Miroslav Pástor',
  ],
  'MOST - HÍD': [
    'József Nagy',
    'Norbert Kurilla',
    'Andrea Vitkóová',
    'Michal Goriščák',
    'Zuzana Csadyová',
    'Gabriel Csicsai',
    'Jozef Želinský',
    'Attila Agócs',
    'Pavol Burdiga',
    'Erika Halašová',
    'Marián Tóth',
    'Ágnes Héder',
    'Richard Šarközi',
    'Csaba Csízi',
  ],
  'PRIAMA DEMOKRACIA': [
    'Ibrahim Maiga',
    'Alojz Hančin',
    'Otília Hamacková',
    'Miroslav Sečany',
  ],
  'Strana rómskej koalície - SRK': [
    'Alfonz Kaliaš',
  ],
  'Slovenská konzervatívna strana': [
    'Igor Adamec',
    'Daniel Mikolaj',
    'Kristína Šabíková',
  ],
  'Slovenská národná jednota - strana vlastencov': [
    'Stanislav Pánis',
    'Ľudovít Líška',
    'Jana Lachkovičová',
    'Jaromír Okša',
    'Jozef Zima',
    'Juraj Mezei',
    'Ladislav Cibulya',
    'Andrea Justusová',
    'Marian Bukoven',
    'Dagmar Weissabelová',
    'Milan Kršiak',
  ],
  'Strana maďarskej komunity': [
    'Pál Csáky',
    'József Berényi',
    'Ákos Horony',
    'Balázs Tárnok',
    'Enikő Mag Fodor',
    'Dávid Nagy',
    'Adrianna Gergely Papp',
    'Zoltán Huďár',
    'Zsolt Baranyay',
    'Anikó Mészáros',
    'Zoltán Környi',
    'Bence Endre Hajdók',
    'Tamás Várady',
    'Lilla Bartalos Szerencsés',
  ],
  'Doma dobre': [
    'Štefan Adam',
    'Helena Mezenská',
    'Zuzana Valocká',
    'Roman Chudý',
    'Jana Špuntová',
    'Zoltán Bíró',
    'Marián Biskupič',
    'Stanislav Irsák',
    'Jana Fabová',
    'Zoltán Ďurčík',
    'Barbora Bugárová',
    'Martin Tehlár',
    'Matej Melicherčík',
    'Asadullah Akbari',
  ],
  'Koalícia strán Komunistická strana Slovenska a VZDOR - strana práce': [
    'Jozef Hrdlička',
    'Jalal Suleiman',
    'Miroslav Pomajdík',
    'Jozef Červeňák',
    'Stanislav Pirošík',
    'Iveta Kohanová',
    'Martin Pákozdy',
    'Michal Kotian',
    'Martin Jágrik',
    'Karol Ondriaš',
    'Ľubomír Jánošík',
    'Ján Chalabala',
    'Peter Badida',
    'Pavol Suško',
  ],
  'Európska demokratická strana': [
    'Antonio Parziale',
    'Erika Adamová',
    'Ľudovít Močulenko',
    'Mária Kmetíková',
    'Marcel Nemec',
    'Alena Longauerová',
    'Tomáš Pristáč',
    'Andrej Berkes',
    'Samuel Letko',
    'Martin Kanza',
    'Hilár Lakatošovie',
    'Jozef Kmeťo',
    'Ján Strkáč',
  ],
  'Sloboda a Solidarita': [
    'Eugen Jurzyca',
    'Alojz Baránik',
    'Lucia Ďuriš Nicholsonová',
    'Natália Blahová',
    'Miroslav Žiak',
    'Ján Rudolf',
    'Karol Ides',
    'Lenka Jakubčová',
    'Michal Kozubík',
    'Karol Galek',
    'Branislav Bukviar',
    'Martina Lopatková',
    'Igor Prieložný',
    'Tomáš Popovič',
  ],
  'Slovenská ľudová strana Andreja Hlinku': [
    'Jozef Sásik',
    'Roman Ruhig',
    'Andrej Trnovec',
    'Štefan Hrušovský',
    'Richard Burkovský',
    'Elena Šubjaková',
    'Pavol Šedivý',
    'Adam Kúkel',
    'Jozef Valovič',
    'Marian Kňažko',
    'Peter Puškár',
    'Miroslav Faktor',
    'Hana Jablonovská',
    'Martin Bálik',
  ],
  'NAJ – Nezávislosť a Jednota': [
    'Branislav Grimm',
    'Ľubomír Moravčík',
    'Anton Gajdoš',
    'Zuzana Kúdelková',
    'Emil Samko',
    'Štefan Mirga',
    'Radoslav Ščuka',
    'Vladimír Bálint',
    'Jozef Zaťko',
    'Peter Hlucháň',
    'Roman Čonka',
    'Roman Hílek',
    'Anton Berczy',
    'Marek Baláž',
  ],
  'Kresťanská únia': [
    'Anna Záborská',
    'Branislav Škripek',
    'Lýdia Pilková',
    'Lukáš Ronec',
    'Peter Broz',
    'Daniel Šobr',
    'Lucia Baranová Maliňáková',
    'Martin Smrčo',
    'Miroslav Baník',
    'Alena Harvanová',
    'Daniel Lukáč',
  ],
  'Koalícia Progresívne Slovensko, SPOLU – občianska demokracia': [
    'Michal Šimečka',
    'Vladimír Bilčík',
    'Simona Petrík',
    'Zora Jaurová',
    'Pavel Macko',
    'Martin Hojsík',
    'Michal Wiezik',
    'Ondrej Prostredník',
    'Tomáš Dentico',
    'Lucia Kleštincová',
    'Emília Mesarošová',
    'Michal Liptaj',
    'Dominik Hatiar',
    'Jozef Mihál',
  ],
  'Demokratická strana': [
    'Michal Kravčík',
    'Jela Tvrdoňová',
    'Pavol Gašper',
    'Martina Vaško Sabolová',
    'Ján Greššo',
    'Erika Várošová',
    'Dušan Katuščák',
    'Ivan Matušek',
    'Milan Michalič',
    'Robert Bezek',
    'Roman Krištín',
    'Vladislav Kačmár',
    'Igor Hornák',
    'Juraj Hríb',
  ],
  'Národná koalícia': [
    'Peter Tomeček',
    'Anton Martvoň',
    'Slavomír Harabin',
    'Radovan Znášik',
    'Marieta Okenková',
    'Marta Rácová',
    'Marián Rusznyák',
    'Sergej Kozlík',
    'Ľubica Blašková',
    'Peter Švec',
    'Juraj Srnec',
    'Ján Piľa',
    'Petra Margušová',
    'Andrej Gmitter',
  ],
}
