export default [
    'Strana TIP',
    'STRANA MODERNÉHO SLOVENSKA (SMS)',
    'OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO - NOVA)',
    'Demokrati Slovenska - Ľudo Kaník',
    'ŠANCA',
    'SME RODINA - Boris Kollár',
    'Strana zelených Slovenska',
    'KOALÍCIA SPOLOČNE ZA SLOVENSKO',
    'Maďarská kresťanskodemokratická aliancia',
    'VZDOR - strana práce',
    'MOST - HÍD',
    'Slovenská národná strana (SNS)',
    'Odvaha - Veľká národná a proruská koalícia',
    'Komunistická strana Slovenska',
    'Slovenská demokratická a kresťanská únia - Demokratická strana',
    'SMER - SD',
    'Kresťanskodemokratické hnutie (KDH)',
    'Slovenská občianska koalícia (SKOK)',
    'Kotleba - Ľudová strana Naše Slovensko (ĽS NS)',
    '#SIEŤ',
    'Strana maďarskej komunity',
    'PRIAMA DEMOKRACIA',
    'Sloboda a Solidarita',
]
